/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portforward;

import java.awt.AWTException;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.io.IOException;

/**
 *
 * @author Sunnybat
 */
public class GUI extends javax.swing.JFrame {

  SystemTray tray;
  TrayIcon myIcon;
  java.awt.Image myImage;
  IconMenu menu;

  /**
   * Creates new form GUI
   */
  public GUI() {
    initComponents();
    customComponents();
  }

  private void customComponents() {
    this.setLocationRelativeTo(null);
    tray = SystemTray.getSystemTray();
    menu = new IconMenu();
    try {
      myImage = javax.imageio.ImageIO.read(PortForward.class.getResourceAsStream("/resources/Icon.png"));
      setIconImage(myImage);
      myIcon = new TrayIcon(myImage, "Portfowarding Tool", menu);
      myIcon.setImageAutoSize(true);
      myIcon.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          maximizeWindow();
        }
      });
    } catch (IOException iOException) {
      iOException.printStackTrace();
    }
  }

  public void minimizeWindow() {
    try {
      jSpinner1.commitEdit(); // Update the spinner value. If invalid, uses the last known valid value (keypresses don't update the last known value)
      if (PortForward.isPortOpen()) {
        menu.addClosePortButton((int) jSpinner1.getValue());
      } else {
        menu.addOpenPortButton((int) jSpinner1.getValue());
      }
      tray.add(myIcon);
    } catch (Exception e) {
      e.printStackTrace();
    }
    setVisible(false);
  }

  public void maximizeWindow() {
    setExtendedState(javax.swing.JFrame.NORMAL);
    setVisible(true);
    this.setLocationRelativeTo(null);
    this.toFront();
    tray.remove(myIcon);
  }

  @Override
  public void dispose() {
    PortForward.closePort();
    tray.remove(myIcon);
    super.dispose();
  }

  public void callButtonAction() {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jButton1ActionPerformed(null);
      }
    });
  }

  public void setPortStatusText(final String text) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        JLPortStatus.setText(text);
      }
    });
  }

  public void setButtonEnabled(final boolean enabled) {
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        jButton1.setEnabled(enabled);
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jSpinner1 = new javax.swing.JSpinner();
    jButton1 = new javax.swing.JButton();
    JLPortStatus = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    addWindowStateListener(new java.awt.event.WindowStateListener() {
      public void windowStateChanged(java.awt.event.WindowEvent evt) {
        formWindowStateChanged(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Portforwarding");

    jLabel2.setText("Port to Portforward:");

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 65535, 1));
    jSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner1, "0"));

    jButton1.setText("GO!");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    JLPortStatus.setText("Port Status:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(JLPortStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 208, Short.MAX_VALUE))
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(JLPortStatus)
        .addGap(18, 18, 18)
        .addComponent(jButton1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    if (!PortForward.isPortOpen()) {
      if (PortForward.openPort((int) jSpinner1.getValue())) {
        jButton1.setText("Close Port!");
      }
    } else {
      jButton1.setText("GO!");
      PortForward.closePort();
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
    // TODO add your handling code here:
    if (getExtendedState() == javax.swing.JFrame.ICONIFIED) {
      minimizeWindow();
    }
  }//GEN-LAST:event_formWindowStateChanged

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private volatile javax.swing.JLabel JLPortStatus;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private volatile javax.swing.JSpinner jSpinner1;
  // End of variables declaration//GEN-END:variables
}
