/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portforward;

/**
 *
 * @author Sunnybat
 */
public class PortPanel extends javax.swing.JPanel {

  private GUI myGUI;

  /**
   * Creates new form PortPanel
   *
   * @param gui The GUI object that this panel has been added to
   */
  public PortPanel(GUI gui) {
    initComponents();
    myGUI = gui;
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    jSpinner1 = new javax.swing.JSpinner();
    JCBTCP = new javax.swing.JCheckBox();
    JCBUDP = new javax.swing.JCheckBox();
    jButton1 = new javax.swing.JButton();

    jLabel2.setText("Port to Portforward:");

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 65535, 1));
    jSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner1, "0"));

    JCBTCP.setSelected(true);
    JCBTCP.setText("TCP");
    JCBTCP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JCBTCPActionPerformed(evt);
      }
    });

    JCBUDP.setSelected(true);
    JCBUDP.setText("UDP");
    JCBUDP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JCBUDPActionPerformed(evt);
      }
    });

    jButton1.setText("Remove Port");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(JCBTCP)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(JCBUDP)
        .addGap(18, 18, 18)
        .addComponent(jButton1))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jLabel2)
        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(JCBTCP)
        .addComponent(JCBUDP)
        .addComponent(jButton1))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void JCBTCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBTCPActionPerformed
    // TODO add your handling code here:
    if (!JCBTCP.isSelected() && !JCBUDP.isSelected()) {
      jButton1.setEnabled(false);
    } else {
      jButton1.setEnabled(true);
    }
  }//GEN-LAST:event_JCBTCPActionPerformed

  private void JCBUDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBUDPActionPerformed
    // TODO add your handling code here:
    if (!JCBTCP.isSelected() && !JCBUDP.isSelected()) {
      jSpinner1.setEnabled(false);
    } else {
      jSpinner1.setEnabled(true);
    }
  }//GEN-LAST:event_JCBUDPActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    myGUI.removePortPanel(this);
  }//GEN-LAST:event_jButton1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JCheckBox JCBTCP;
  public javax.swing.JCheckBox JCBUDP;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel2;
  public javax.swing.JSpinner jSpinner1;
  // End of variables declaration//GEN-END:variables
}
